### ISSUE TITLE
Raw data unavailability

### ISSUE THREAD

**Issue by pinunQ** [heiniglab/DCM_heart_cell_atlas#2]
Hello, 

I loved your work and the paper is very insightful, however I was looking over the raw data unavailability on the EGA portal.

I believe you can provide me some information where I can get the data from?

**Comment by Elhl93** [comment]
Hi, 

many thanks for your interest in the dataset. 

Unfortunately there is an issue which needs to be solved by EGA, we informed them already. Hopefully this will be fixed by EGA soon. 

An easy solution might be to access the count matrices from zenodo: 
https://zenodo.org/record/6962685#.YuyuihxBzKE (see also README in this repo)

In case you want to work with the fastq/bam files, there is the possibility to send you the data via FTP. However, as the patient data from Germany underlie the German General Data Protection Regulation (GDPR), a data access agreement (DAA) is needed first. 

If you send an Email to me ([eric.lindberg@mdc-berlin.de](mailto:eric.lindberg@mdc-berlin.de)) or all corresponding authors, we are happy to bring you in contact with the responsible person.
